# Generated by Django 5.0.6 on 2024-07-06 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0002_back_cam_back_cam_front_cam_front_cam_mobile_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='mobile_store.mobile')),
            ],
        ),
    ]
