# Generated by Django 5.0.6 on 2024-07-09 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0007_checkout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None)),
                ('mobile_number', models.CharField(default=None)),
                ('email', models.CharField(default=None)),
                ('village', models.CharField(default=None)),
                ('state', models.CharField(default=None)),
                ('city', models.CharField(default=None)),
                ('colony', models.CharField(default=None)),
                ('pin_code', models.CharField(default=None)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
