# Generated by Django 5.0.6 on 2024-07-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_store', '0009_cart_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart_orders',
        ),
    ]
